# volumes:
#   sqlserver_data:

services:
  sqlserver:
    # image: mcr.microsoft.com/mssql/server:2022-latest
    # image: mcr.microsoft.com/mssql/server:2017-latest
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=83edb36d-f757-4f0d-9ed3-d31299b993dc
      # - MSSQL_PID=Developer
    ports:
      - 1433:1433
    # volumes:
    #   - sqlserver_data:/var/opt/mssql
    # restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "sqlcmd.exe -S localhost -U sa -P c83edb36d-f757-4f0d-9ed3-d31299b993dc -Q 'SELECT 1' || exit 1"]
    #   interval: 10s
    #   retries: 10
    #   start_period: 10s
    #   timeout: 3s
  # sqlserver.configurator:
  #   image: mcr.microsoft.com/mssql/server
  #   volumes:
  #     - ./init:/docker-entrypoint-initdb.d
  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy
  #   command: >
  #     bash -c '
  #     sqlcmd.exe -S localhost:1433 -U sa -P c83edb36d-f757-4f0d-9ed3-d31299b993dc -d master -i docker-entrypoint-initdb.d/init.sql;
  #     echo "All done!";
  #     '